version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - STACKHERO_REDIS_URL_TLS
    depends_on:
      - web
